Importing

In [2]:
import numpy as np
import random
import pandas as pd

Numpy

In [2]:
a=np.arange(15)
print(a)
print(a.reshape(3,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a.shape

(15,)

In [4]:
a=a.reshape(3,5)

In [5]:
a.dtype.name

'int32'

In [6]:
a.ndim

2

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a=np.ones(2)

In [9]:
a

array([1., 1.])

In [10]:
a=np.eye(4)

In [11]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
a=np.empty(5)

In [13]:
a

array([2.12199579e-314, 4.67296746e-307, 5.53353523e-321, 1.51298300e-311,
       2.42092166e-322])

In [14]:
a=np.arange(24)

In [15]:
a=a.reshape(3,2,4)

In [16]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
b,c=np.random.random((2,4)),np.random.random((2,4))

In [18]:
print(b);print();print(c)
print("\n\n")
print(b+c)

[[0.987486   0.01909179 0.32185985 0.06191212]
 [0.9865077  0.7354031  0.50237941 0.66608412]]

[[0.06214838 0.23118184 0.67197345 0.15748891]
 [0.91180918 0.3668811  0.93045876 0.94933332]]



[[1.04963438 0.25027363 0.9938333  0.21940103]
 [1.89831688 1.1022842  1.43283816 1.61541744]]


In [19]:
print(b-c)
print(b*c)
print(b/c)

[[ 0.92533761 -0.21209005 -0.35011361 -0.09557679]
 [ 0.07469852  0.368522   -0.42807935 -0.2832492 ]]
[[0.06137066 0.00441367 0.21628127 0.00975047]
 [0.89950678 0.2698055  0.46744332 0.63233585]]
[[15.88916626  0.08258343  0.47897703  0.39312052]
 [ 1.08192341  2.00447258  0.53992657  0.70163356]]


In [34]:
arr=np.arange(30)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
arr=arr.reshape(5,3,2)

In [37]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [38]:
arr=np.random.randn(12)

In [39]:
arr

array([ 1.98751719,  1.59589764,  0.69727733,  0.57688427,  2.61769905,
        0.26316682,  0.53998765,  2.03382678, -0.5089186 ,  0.08619195,
        0.05235419, -0.05908008])

In [42]:
np.random.randint(15)

7

In [43]:
np.sqrt(arr)

C:\Users\SREERAM\AppData\Local\Temp\ipykernel_17252\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.40979331, 1.26328842, 0.83503134, 0.75952898, 1.61793048,
       0.51299788, 0.73483852, 1.42612299,        nan, 0.29358466,
       0.22881039,        nan])

In [44]:
np.exp(arr)

array([ 7.29739319,  4.9327549 ,  2.00827738,  1.78048227, 13.70415467,
        1.30104374,  1.71598567,  7.64327962,  0.60114531,  1.09001554,
        1.05374891,  0.94263128])

In [7]:
series=pd.Series([1,2,34,'hello','hi'],index=[1,2,3,4,5])

In [8]:
series

1        1
2        2
3       34
4    hello
5       hi
dtype: object

In [9]:
type(series)

pandas.core.series.Series

In [28]:
placement=pd.read_csv('placement-dataset.csv')

In [13]:
placement.columns

Index(['Unnamed: 0', 'cgpa', 'iq', 'placement'], dtype='object')

In [18]:
placement.head(3)

Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0

In [24]:
placement[(placement['cgpa']>7) & (placement['iq']>100.0)]

Unnamed: 0  cgpa     iq  placement
3            3   7.4  132.0          1
21          21   7.1  151.0          1
30          30   7.6  128.0          1
37          37   8.1  149.0          1
53          53   8.3  168.0          1
55          55   7.8  114.0          1
61          61   7.3  137.0          1
65          65   8.1  166.0          1
69          69   8.5  120.0          1
72          72   7.3  116.0          1
83          83   7.5  130.0          1
91          91   7.5  158.0          1

In [3]:
my_series=pd.Series({'Washington':12,'NewYork':100})

In [4]:
my_series[my_series<100]

Washington    12
dtype: int64

In [7]:
my_series.shape

(2,)

In [14]:
s1=pd.Series(np.random.randn(5), index=['a','b','c','d','e'])

In [13]:
s1

a   -0.144265
b    0.986362
c   -1.639103
d    1.121028
e    0.743483
dtype: float64

In [17]:
s2=pd.Series(np.random.randn(5), index=['a','b','c','d','e'])
pd.concat([s1,s2])

a    0.058093
b    0.973730
c    1.166621
d   -1.038574
e   -0.301196
a    0.279179
b   -1.145107
c   -0.269338
d   -0.012203
e    1.161634
dtype: float64

In [20]:
con=pd.concat([s1,s2], axis=1)

In [19]:
pd.concat([s1,s2], axis=1).reset_index()

index         0         1
0     a  0.058093  0.279179
1     b  0.973730 -1.145107
2     c  1.166621 -0.269338
3     d -1.038574 -0.012203
4     e -0.301196  1.161634

In [22]:
con.iloc[2,1]

-0.26933847778627873

In [26]:
df=pd.DataFrame(np.random.randn(25).reshape((5,5)))

In [27]:
df

0         1         2         3         4
0 -0.399822 -0.813561 -0.316746 -1.164749  0.626567
1 -1.250829 -0.243730  0.266728 -0.615876  1.404880
2 -1.769507  0.191896 -0.210156 -0.797837  1.057229
3  1.657358 -0.538100  1.367079  0.219593 -0.280855
4 -1.638574 -0.512831 -1.452830  0.670577  0.687881

In [30]:
type(placement)

pandas.core.frame.DataFrame